# Generated by Django 5.2.7 on 2025-11-02 09:55

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('original_url', models.URLField(max_length=2048, verbose_name='Original URL')),
                ('short_code', models.CharField(db_index=True, help_text='Unique short code for the URL', max_length=20, unique=True, verbose_name='Short Code')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Click Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the short URL', null=True, verbose_name='Expires At')),
                ('user', models.ForeignKey(blank=True, help_text='User who created this short URL (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Short URL',
                'verbose_name_plural': 'Short URLs',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['short_code'], name='urlshortene_short_c_d81072_idx'), models.Index(fields=['user', '-created'], name='urlshortene_user_id_62fd3f_idx')],
            },
        ),
    ]
