openapi: 3.0.3
info:
  title: Vinta Boilerplate API
  version: 0.1.0
  description: A Django project boilerplate with Vinta's best practices
paths:
  /api/auth/user/:
    get:
      operationId: auth_user_retrieve
      description: Get current authenticated user info.
      tags:
      - auth
      security:
      - cookieAuth: []
      responses:
        '200':
          description: No response body
  /api/rest/:
    get:
      operationId: rest_retrieve
      description: Basic REST viewset for testing.
      tags:
      - rest
      security:
      - cookieAuth: []
      responses:
        '200':
          description: No response body
  /api/short-urls/:
    get:
      operationId: short_urls_list
      description: ViewSet for ShortURL operations.
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - short-urls
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedShortURLList'
          description: ''
    post:
      operationId: short_urls_create
      description: ViewSet for ShortURL operations.
      tags:
      - short-urls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortURLCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ShortURLCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ShortURLCreate'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortURLCreate'
          description: ''
  /api/short-urls/{id}/:
    get:
      operationId: short_urls_retrieve
      description: ViewSet for ShortURL operations.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Short URL.
        required: true
      tags:
      - short-urls
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortURL'
          description: ''
    put:
      operationId: short_urls_update
      description: ViewSet for ShortURL operations.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Short URL.
        required: true
      tags:
      - short-urls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortURL'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ShortURL'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ShortURL'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortURL'
          description: ''
    patch:
      operationId: short_urls_partial_update
      description: ViewSet for ShortURL operations.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Short URL.
        required: true
      tags:
      - short-urls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedShortURL'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedShortURL'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedShortURL'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortURL'
          description: ''
    delete:
      operationId: short_urls_destroy
      description: ViewSet for ShortURL operations.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Short URL.
        required: true
      tags:
      - short-urls
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/short-urls/{id}/stats/:
    get:
      operationId: short_urls_stats_retrieve
      description: Get statistics for a short URL.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Short URL.
        required: true
      tags:
      - short-urls
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortURL'
          description: ''
  /api/short-urls/shorten/:
    post:
      operationId: short_urls_shorten_create
      description: Public endpoint to create short URLs.
      tags:
      - short-urls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortURL'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ShortURL'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ShortURL'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortURL'
          description: ''
components:
  schemas:
    PaginatedShortURLList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/ShortURL'
    PatchedShortURL:
      type: object
      description: Serializer for ShortURL model.
      properties:
        id:
          type: integer
          readOnly: true
        original_url:
          type: string
          format: uri
          maxLength: 2048
        short_code:
          type: string
          readOnly: true
          description: Unique short code for the URL
        short_url:
          type: string
          readOnly: true
        user:
          type: integer
          nullable: true
          description: User who created this short URL (optional)
        user_email:
          type: string
          format: email
          readOnly: true
        click_count:
          type: integer
          readOnly: true
        is_active:
          type: boolean
        expires_at:
          type: string
          format: date-time
          nullable: true
          description: Optional expiration date for the short URL
        created:
          type: string
          format: date-time
          readOnly: true
        modified:
          type: string
          format: date-time
          readOnly: true
    ShortURL:
      type: object
      description: Serializer for ShortURL model.
      properties:
        id:
          type: integer
          readOnly: true
        original_url:
          type: string
          format: uri
          maxLength: 2048
        short_code:
          type: string
          readOnly: true
          description: Unique short code for the URL
        short_url:
          type: string
          readOnly: true
        user:
          type: integer
          nullable: true
          description: User who created this short URL (optional)
        user_email:
          type: string
          format: email
          readOnly: true
        click_count:
          type: integer
          readOnly: true
        is_active:
          type: boolean
        expires_at:
          type: string
          format: date-time
          nullable: true
          description: Optional expiration date for the short URL
        created:
          type: string
          format: date-time
          readOnly: true
        modified:
          type: string
          format: date-time
          readOnly: true
      required:
      - click_count
      - created
      - id
      - modified
      - original_url
      - short_code
      - short_url
      - user_email
    ShortURLCreate:
      type: object
      description: Serializer for creating short URLs.
      properties:
        original_url:
          type: string
          format: uri
        custom_code:
          type: string
          description: Optional custom short code (must be unique)
          maxLength: 20
        expires_at:
          type: string
          format: date-time
          nullable: true
      required:
      - original_url
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
