// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthUserRetrieveData, AuthUserRetrieveResponses, RestRetrieveData, RestRetrieveResponses, ShortUrlsCreateData, ShortUrlsCreateResponses, ShortUrlsDestroyData, ShortUrlsDestroyResponses, ShortUrlsListData, ShortUrlsListResponses, ShortUrlsPartialUpdateData, ShortUrlsPartialUpdateResponses, ShortUrlsRetrieveData, ShortUrlsRetrieveResponses, ShortUrlsShortenCreateData, ShortUrlsShortenCreateResponses, ShortUrlsStatsRetrieveData, ShortUrlsStatsRetrieveResponses, ShortUrlsUpdateData, ShortUrlsUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get current authenticated user info.
 */
export const authUserRetrieve = <ThrowOnError extends boolean = false>(options?: Options<AuthUserRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<AuthUserRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/auth/user/',
        ...options
    });
};

/**
 * Basic REST viewset for testing.
 */
export const restRetrieve = <ThrowOnError extends boolean = false>(options?: Options<RestRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<RestRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/rest/',
        ...options
    });
};

/**
 * ViewSet for ShortURL operations.
 */
export const shortUrlsList = <ThrowOnError extends boolean = false>(options?: Options<ShortUrlsListData, ThrowOnError>) => {
    return (options?.client ?? client).get<ShortUrlsListResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/short-urls/',
        ...options
    });
};

/**
 * ViewSet for ShortURL operations.
 */
export const shortUrlsCreate = <ThrowOnError extends boolean = false>(options: Options<ShortUrlsCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ShortUrlsCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/short-urls/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * ViewSet for ShortURL operations.
 */
export const shortUrlsDestroy = <ThrowOnError extends boolean = false>(options: Options<ShortUrlsDestroyData, ThrowOnError>) => {
    return (options.client ?? client).delete<ShortUrlsDestroyResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/short-urls/{id}/',
        ...options
    });
};

/**
 * ViewSet for ShortURL operations.
 */
export const shortUrlsRetrieve = <ThrowOnError extends boolean = false>(options: Options<ShortUrlsRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ShortUrlsRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/short-urls/{id}/',
        ...options
    });
};

/**
 * ViewSet for ShortURL operations.
 */
export const shortUrlsPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<ShortUrlsPartialUpdateData, ThrowOnError>) => {
    return (options.client ?? client).patch<ShortUrlsPartialUpdateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/short-urls/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * ViewSet for ShortURL operations.
 */
export const shortUrlsUpdate = <ThrowOnError extends boolean = false>(options: Options<ShortUrlsUpdateData, ThrowOnError>) => {
    return (options.client ?? client).put<ShortUrlsUpdateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/short-urls/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get statistics for a short URL.
 */
export const shortUrlsStatsRetrieve = <ThrowOnError extends boolean = false>(options: Options<ShortUrlsStatsRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ShortUrlsStatsRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/short-urls/{id}/stats/',
        ...options
    });
};

/**
 * Public endpoint to create short URLs.
 */
export const shortUrlsShortenCreate = <ThrowOnError extends boolean = false>(options: Options<ShortUrlsShortenCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ShortUrlsShortenCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/short-urls/shorten/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
