// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type PaginatedShortUrlList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ShortUrl>;
};

/**
 * Serializer for ShortURL model.
 */
export type PatchedShortUrl = {
    readonly id?: number;
    original_url?: string;
    /**
     * Unique short code for the URL
     */
    readonly short_code?: string;
    readonly short_url?: string;
    /**
     * User who created this short URL (optional)
     */
    user?: number | null;
    readonly user_email?: string;
    readonly click_count?: number;
    is_active?: boolean;
    /**
     * Optional expiration date for the short URL
     */
    expires_at?: string | null;
    readonly created?: string;
    readonly modified?: string;
};

/**
 * Serializer for ShortURL model.
 */
export type ShortUrl = {
    readonly id: number;
    original_url: string;
    /**
     * Unique short code for the URL
     */
    readonly short_code: string;
    readonly short_url: string;
    /**
     * User who created this short URL (optional)
     */
    user?: number | null;
    readonly user_email: string;
    readonly click_count: number;
    is_active?: boolean;
    /**
     * Optional expiration date for the short URL
     */
    expires_at?: string | null;
    readonly created: string;
    readonly modified: string;
};

/**
 * Serializer for creating short URLs.
 */
export type ShortUrlCreate = {
    original_url: string;
    /**
     * Optional custom short code (must be unique)
     */
    custom_code?: string;
    expires_at?: string | null;
};

/**
 * Serializer for ShortURL model.
 */
export type PatchedShortUrlWritable = {
    original_url?: string;
    /**
     * User who created this short URL (optional)
     */
    user?: number | null;
    is_active?: boolean;
    /**
     * Optional expiration date for the short URL
     */
    expires_at?: string | null;
};

/**
 * Serializer for ShortURL model.
 */
export type ShortUrlWritable = {
    original_url: string;
    /**
     * User who created this short URL (optional)
     */
    user?: number | null;
    is_active?: boolean;
    /**
     * Optional expiration date for the short URL
     */
    expires_at?: string | null;
};

export type AuthUserRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/user/';
};

export type AuthUserRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type RestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rest/';
};

export type RestRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ShortUrlsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/short-urls/';
};

export type ShortUrlsListResponses = {
    200: PaginatedShortUrlList;
};

export type ShortUrlsListResponse = ShortUrlsListResponses[keyof ShortUrlsListResponses];

export type ShortUrlsCreateData = {
    body: ShortUrlCreate;
    path?: never;
    query?: never;
    url: '/api/short-urls/';
};

export type ShortUrlsCreateResponses = {
    201: ShortUrlCreate;
};

export type ShortUrlsCreateResponse = ShortUrlsCreateResponses[keyof ShortUrlsCreateResponses];

export type ShortUrlsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Short URL.
         */
        id: number;
    };
    query?: never;
    url: '/api/short-urls/{id}/';
};

export type ShortUrlsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ShortUrlsDestroyResponse = ShortUrlsDestroyResponses[keyof ShortUrlsDestroyResponses];

export type ShortUrlsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Short URL.
         */
        id: number;
    };
    query?: never;
    url: '/api/short-urls/{id}/';
};

export type ShortUrlsRetrieveResponses = {
    200: ShortUrl;
};

export type ShortUrlsRetrieveResponse = ShortUrlsRetrieveResponses[keyof ShortUrlsRetrieveResponses];

export type ShortUrlsPartialUpdateData = {
    body?: PatchedShortUrlWritable;
    path: {
        /**
         * A unique integer value identifying this Short URL.
         */
        id: number;
    };
    query?: never;
    url: '/api/short-urls/{id}/';
};

export type ShortUrlsPartialUpdateResponses = {
    200: ShortUrl;
};

export type ShortUrlsPartialUpdateResponse = ShortUrlsPartialUpdateResponses[keyof ShortUrlsPartialUpdateResponses];

export type ShortUrlsUpdateData = {
    body: ShortUrlWritable;
    path: {
        /**
         * A unique integer value identifying this Short URL.
         */
        id: number;
    };
    query?: never;
    url: '/api/short-urls/{id}/';
};

export type ShortUrlsUpdateResponses = {
    200: ShortUrl;
};

export type ShortUrlsUpdateResponse = ShortUrlsUpdateResponses[keyof ShortUrlsUpdateResponses];

export type ShortUrlsStatsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Short URL.
         */
        id: number;
    };
    query?: never;
    url: '/api/short-urls/{id}/stats/';
};

export type ShortUrlsStatsRetrieveResponses = {
    200: ShortUrl;
};

export type ShortUrlsStatsRetrieveResponse = ShortUrlsStatsRetrieveResponses[keyof ShortUrlsStatsRetrieveResponses];

export type ShortUrlsShortenCreateData = {
    body: ShortUrlWritable;
    path?: never;
    query?: never;
    url: '/api/short-urls/shorten/';
};

export type ShortUrlsShortenCreateResponses = {
    200: ShortUrl;
};

export type ShortUrlsShortenCreateResponse = ShortUrlsShortenCreateResponses[keyof ShortUrlsShortenCreateResponses];
